[package]
name = "backend-rust"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-web = "4.9.0"
actix-ws = "0.3.0"
futures-util = "0.3.30"
tokio = { version = "1.40.0", features = ["macros", "rt-multi-thread"] }
